// AUTO-GENERATED by scripts/generate-sdk.ts from src/server/openapi.ts — DO NOT EDIT BY HAND.
// Regenerate: bun run scripts/generate-sdk.ts

// @generated from OpenAPI by @hasna/contracts SDK generator — DO NOT EDIT.
// Source: Calendar API 0.1.14

export interface Org { "id": string; "name": string; "slug": string; "description"?: string; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface CreateOrgInput { "name": string; "slug"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface UpdateOrgInput { "name"?: string; "description"?: string; "metadata"?: Record<string, unknown> }

export interface Calendar { "id": string; "org_id": string; "owner_id"?: string; "slug": string; "name": string; "description"?: string; "color"?: string; "timezone": string; "visibility": "public" | "org" | "private"; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface CreateCalendarInput { "org_id": string; "owner_id"?: string; "name": string; "slug"?: string; "description"?: string; "color"?: string; "timezone"?: string; "visibility"?: "public" | "org" | "private"; "metadata"?: Record<string, unknown> }

export interface UpdateCalendarInput { "name"?: string; "description"?: string; "color"?: string; "timezone"?: string; "visibility"?: "public" | "org" | "private"; "metadata"?: Record<string, unknown> }

export interface Event { "id": string; "calendar_id": string; "org_id": string; "title": string; "description"?: string; "location"?: string; "start_at": string; "end_at": string; "all_day"?: boolean; "timezone"?: string; "status"?: "tentative" | "confirmed" | "cancelled"; "busy_type"?: "busy" | "free" | "out_of_office"; "visibility"?: "default" | "private" | "confidential"; "recurrence_rule"?: string; "recurrence_exception_dates"?: Array<string>; "source_task_id"?: string; "created_by"?: string; "metadata"?: Record<string, unknown>; "created_at"?: string; "updated_at"?: string }

export interface CreateEventInput { "calendar_id": string; "org_id": string; "title": string; "description"?: string; "location"?: string; "start_at": string; "end_at": string; "all_day"?: boolean; "timezone"?: string; "status"?: "tentative" | "confirmed" | "cancelled"; "busy_type"?: "busy" | "free" | "out_of_office"; "visibility"?: "default" | "private" | "confidential"; "recurrence_rule"?: string; "recurrence_exception_dates"?: Array<string>; "source_task_id"?: string; "created_by"?: string; "metadata"?: Record<string, unknown> }

export interface UpdateEventInput { "title"?: string; "description"?: string; "location"?: string; "start_at"?: string; "end_at"?: string; "all_day"?: boolean; "timezone"?: string; "status"?: "tentative" | "confirmed" | "cancelled"; "busy_type"?: "busy" | "free" | "out_of_office"; "visibility"?: "default" | "private" | "confidential"; "recurrence_rule"?: string; "recurrence_exception_dates"?: Array<string>; "source_task_id"?: string; "metadata"?: Record<string, unknown> }

export interface Attendee { "id": string; "event_id": string; "agent_id"?: string; "display_name"?: string; "email"?: string; "status": "needsAction" | "accepted" | "declined" | "tentative"; "required"?: boolean; "response_comment"?: string; "responded_at"?: string; "created_at"?: string }

export interface CreateAttendeeInput { "event_id": string; "agent_id"?: string; "display_name"?: string; "email"?: string; "status"?: "needsAction" | "accepted" | "declined" | "tentative"; "required"?: boolean }

export interface Agent { "id": string; "name": string; "description"?: string; "role"?: string; "status"?: string; "metadata"?: Record<string, unknown>; "created_at"?: string; "last_seen_at"?: string }

export interface RegisterAgentInput { "name": string; "description"?: string; "role"?: string; "title"?: string; "level"?: string; "org_id"?: string }

export interface Availability { "id": string; "agent_id": string; "org_id": string; "day_of_week": number; "start_time": string; "end_time": string; "exceptions"?: Array<string>; "created_at"?: string; "updated_at"?: string }

export interface UpsertAvailabilityInput { "agent_id": string; "org_id": string; "day_of_week": number; "start_time": string; "end_time": string }

export interface Membership { "id": string; "org_id": string; "agent_id": string; "role": "admin" | "member" | "service"; "created_at"?: string }

export interface CreateMembershipInput { "org_id": string; "agent_id": string; "role"?: "admin" | "member" | "service" }

export interface DeleteResult { "deleted": boolean }

export interface Error { "error": string }

export interface CalendarV1ClientOptions {
  /** Base URL, e.g. process.env.APP_API_URL. */
  baseUrl: string;
  /** API key, e.g. process.env.APP_API_KEY. Sent as the 'x-api-key' header. */
  apiKey?: string;
  /** Custom fetch (defaults to global fetch). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
}

export class ApiError extends Error {
  constructor(readonly status: number, message: string, readonly body: unknown) {
    super(message);
    this.name = "ApiError";
  }
}

export class CalendarV1Client {
  private readonly baseUrl: string;
  private readonly apiKey: string | undefined;
  private readonly fetchImpl: typeof fetch;
  private readonly baseHeaders: Record<string, string>;

  constructor(options: CalendarV1ClientOptions) {
    if (!options.baseUrl) throw new Error("CalendarV1Client requires a baseUrl.");
    this.baseUrl = options.baseUrl.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.baseHeaders = options.headers ?? {};
  }

  private async request<T>(method: string, path: string, opts: { body?: unknown; query?: Record<string, unknown>; init?: RequestInit }): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (opts.query) {
      for (const [key, value] of Object.entries(opts.query)) {
        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));
      }
    }
    const headers: Record<string, string> = { Accept: "application/json", ...this.baseHeaders, ...(opts.init?.headers as Record<string, string> | undefined) };
    if (this.apiKey) headers["x-api-key"] = this.apiKey;
    let payload: BodyInit | undefined;
    if (opts.body !== undefined) {
      headers["Content-Type"] = "application/json";
      payload = JSON.stringify(opts.body);
    }
    const response = await this.fetchImpl(url.toString(), { ...opts.init, method, headers, body: payload });
    const text = await response.text();
    const data = text ? (() => { try { return JSON.parse(text); } catch { return text; } })() : undefined;
    if (!response.ok) {
      throw new ApiError(response.status, `${method} ${path} failed: ${response.status}`, data);
    }
    return data as T;
  }

    /** List agents */
    async listAgents(init?: RequestInit): Promise<{ "agents"?: Array<Agent>; "count"?: number }> {
      return this.request("GET", `/v1/agents`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Register (or upsert) an agent */
    async registerAgent(body: RegisterAgentInput, init?: RequestInit): Promise<{ "agent"?: Agent }> {
      return this.request("POST", `/v1/agents`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Add an attendee to an event */
    async addAttendee(body: CreateAttendeeInput, init?: RequestInit): Promise<{ "attendee"?: Attendee }> {
      return this.request("POST", `/v1/attendees`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get availability windows for an agent */
    async getAvailability(query?: { "agent_id": string; "org_id"?: string }, init?: RequestInit): Promise<{ "availability"?: Array<Availability>; "count"?: number }> {
      return this.request("GET", `/v1/availability`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Upsert an agent availability window */
    async upsertAvailability(body: UpsertAvailabilityInput, init?: RequestInit): Promise<{ "availability"?: Availability }> {
      return this.request("POST", `/v1/availability`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List calendars */
    async listCalendars(query?: { "org_id"?: string }, init?: RequestInit): Promise<{ "calendars"?: Array<Calendar>; "count"?: number }> {
      return this.request("GET", `/v1/calendars`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create a calendar */
    async createCalendar(body: CreateCalendarInput, init?: RequestInit): Promise<{ "calendar"?: Calendar }> {
      return this.request("POST", `/v1/calendars`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get a calendar */
    async getCalendar(id: string, init?: RequestInit): Promise<{ "calendar"?: Calendar }> {
      return this.request("GET", `/v1/calendars/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete a calendar */
    async deleteCalendar(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/calendars/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update a calendar */
    async updateCalendar(id: string, body: UpdateCalendarInput, init?: RequestInit): Promise<{ "calendar"?: Calendar }> {
      return this.request("PATCH", `/v1/calendars/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List events */
    async listEvents(query?: { "calendar_id"?: string; "org_id"?: string; "status"?: string; "after"?: string; "before"?: string; "source_task_id"?: string; "limit"?: number }, init?: RequestInit): Promise<{ "events"?: Array<Event>; "count"?: number }> {
      return this.request("GET", `/v1/events`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Create an event */
    async createEvent(body: CreateEventInput, init?: RequestInit): Promise<{ "event"?: Event }> {
      return this.request("POST", `/v1/events`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Find overlapping events in a calendar */
    async findConflicts(query?: { "calendar_id": string; "start": string; "end": string }, init?: RequestInit): Promise<{ "conflicts"?: Array<Event>; "count"?: number }> {
      return this.request("GET", `/v1/events/conflicts`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Full-text search events */
    async searchEvents(query?: { "q": string; "org_id"?: string }, init?: RequestInit): Promise<{ "events"?: Array<Event>; "count"?: number }> {
      return this.request("GET", `/v1/events/search`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Get an event with attendees */
    async getEvent(id: string, init?: RequestInit): Promise<{ "event"?: Event; "attendees"?: Array<Attendee> }> {
      return this.request("GET", `/v1/events/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete an event */
    async deleteEvent(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/events/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update an event */
    async updateEvent(id: string, body: UpdateEventInput, init?: RequestInit): Promise<{ "event"?: Event }> {
      return this.request("PATCH", `/v1/events/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List org memberships */
    async listMembers(query?: { "org_id": string }, init?: RequestInit): Promise<{ "members"?: Array<Membership>; "count"?: number }> {
      return this.request("GET", `/v1/members`, {
        body: undefined,
        query,
        init,
      });
    }

    /** Add an agent to an org */
    async addMember(body: CreateMembershipInput, init?: RequestInit): Promise<{ "member"?: Membership }> {
      return this.request("POST", `/v1/members`, {
        body,
        query: undefined,
        init,
      });
    }

    /** List organizations */
    async listOrgs(init?: RequestInit): Promise<{ "orgs"?: Array<Org>; "count"?: number }> {
      return this.request("GET", `/v1/orgs`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Create an organization */
    async createOrg(body: CreateOrgInput, init?: RequestInit): Promise<{ "org"?: Org }> {
      return this.request("POST", `/v1/orgs`, {
        body,
        query: undefined,
        init,
      });
    }

    /** Get an org by id or slug */
    async getOrg(id: string, init?: RequestInit): Promise<{ "org"?: Org }> {
      return this.request("GET", `/v1/orgs/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Delete an org */
    async deleteOrg(id: string, init?: RequestInit): Promise<DeleteResult> {
      return this.request("DELETE", `/v1/orgs/${encodeURIComponent(String(id))}`, {
        body: undefined,
        query: undefined,
        init,
      });
    }

    /** Update an org */
    async updateOrg(id: string, body: UpdateOrgInput, init?: RequestInit): Promise<{ "org"?: Org }> {
      return this.request("PATCH", `/v1/orgs/${encodeURIComponent(String(id))}`, {
        body,
        query: undefined,
        init,
      });
    }
}
